/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 8.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
/virtual_serial: #虚拟串口
  ros__parameters:
    roll: 0.0
    pitch: 0.0
    yaw: 180.0
    vision_mode: 2

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 1
    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

/ballistic_calculation:
  ros__parameters:
    iteration_coeffcient_first: 0.1  
    iteration_coeffcient_second: 0.05
    air_resistence: 0.1
    bullet_speed: 30.0
    swich_stategy_1: 30.0
    swich_stategy_2: 120.0
    max_v_yaw_PTZ: 1.0
/rune_detector:
  ros__parameters:
      detect_color: 0
      debug: true
      requests_limit: 5 
      detect_r_tag: true # 是否使用传统方法识别R标
      min_lightness: 100 # 二值化亮度阈值 (R标识别)
      detector:
        model: "package://rune_detector/model/yolox_rune_3.6m.onnx" # GPU模式下请用xml文件
        device_type: "CPU"
/rune_solver:
  ros__parameters:
    debug: true
    auto_type_determined: true 
    predict_time: 0.0
    compensator_type: resistance
    gravity: 9.8
    bullet_speet: 28.0
    lost_time_thres: 0.5
    ekf:
      q: [4e-4, 1e-4, 1e-4, 1e-4]
      r: [4e-2, 1e-2, 1e-2, 1e-2]
/rune_ballistic:
  ros__parameters:
    iteration_coeffcient: 0.05
    air_resistence: 0.1
    bullet_speed: 30.0
    odom2gun:
      xyz: [0.0,0.0,0.0]