/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 8.0

/serial_driver:
  ros__parameters:
    timestamp_offset: -0.0025
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true
#0:red;1:blue
    detect_color: 0
    binary_thres: 60

    light.min_ratio: 0.05
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.95
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xy: 0.5
      sigma2_q_z: 0.05
      sigma2_q_yaw: 10.0
      sigma2_q_r: 10.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-3
      r_radius: 0.1

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 0.5

      tracking_thres: 5
      lost_time_thres: 0.3

/ballistic_calculation:
  ros__parameters:
    iteration_coeffcient_first: 0.1  
    iteration_coeffcient_second: 0.05
    air_resistence: 0.1
    ifFireK: 0.02
    bullet_speed: 26.0
    swich_stategy_1: 5.0
    swich_stategy_2: 30.0
    max_v_yaw_PTZ: 1.2
    xyz: [0.03, 0.0, 0.0]
    rpy: [0.0, 0.038, 0.0]